apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prototype.fullname" . }}-config
  labels:
    {{- include "prototype.labels" . | nindent 4 }}
data:
  MINIO_ENDPOINT: "{{ include "prototype.s3.fullname" . }}:9000"

