apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prototype.fullname" . }}-recipes-csi-pvc
  labels:
    {{- include "prototype.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.s3.csiDriver.storageSize }}
  storageClassName: {{ .Values.s3.csiDriver.storageClassName }}
  volumeMode: Filesystem

