apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "veladora.fullname" . }}-config
  labels:
    {{- include "veladora.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ include "veladora.postgres.fullname" . }}"
  DB_PORT: "5432"
  REDIS_HOST: "{{ include "veladora.redis.fullname" . }}"
  REDIS_PORT: "6379"

