apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veladora.fullname" . }}-jwt-secret
  labels:
    {{- include "veladora.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  secret: {{ include "veladora.jwt.secret" . | quote }}

