{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veladora.postgres.fullname" . }}-secret
  labels:
    {{- include "veladora.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
stringData:
  user: {{ include "veladora.postgres.user" . | quote }}
  password: {{ include "veladora.postgres.password" . | quote }}
{{- end }}

