{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veladora.redis.fullname" . }}-secret
  labels:
    {{- include "veladora.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
stringData:
  password: {{ include "veladora.redis.password" . | quote }}
{{- end }}

