{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "veladora.redis.fullname" . }}
  labels:
    {{- include "veladora.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: redis
    port: {{ .Values.redis.service.port }}
    targetPort: redis
    protocol: TCP
  selector:
    {{- include "veladora.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}

