{{- if and .Values.tls.enabled (or .Values.tls.certificate .Values.tls.certificateBase64) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veladora.fullname" . }}-tls
  labels:
    {{- include "veladora.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if .Values.tls.certificate }}
  tls.crt: {{ .Values.tls.certificate | b64enc }}
  {{- else }}
  tls.crt: {{ .Values.tls.certificateBase64 }}
  {{- end }}
  {{- if .Values.tls.key }}
  tls.key: {{ .Values.tls.key | b64enc }}
  {{- else }}
  tls.key: {{ .Values.tls.keyBase64 }}
  {{- end }}
{{- end }}

