{{- if .Values.volumes.secrets.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "archive.fullname" . }}-secrets-pvc
  labels:
    {{- include "archive.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - {{ .Values.volumes.secrets.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volumes.secrets.size }}
  {{- if .Values.volumes.secrets.storageClass }}
  storageClassName: {{ .Values.volumes.secrets.storageClass }}
  {{- end }}
{{- end }}

